apiVersion: batch/v1
kind: Job
metadata:
  name: team-a-job-high
  namespace: team-a
  labels:
    kueue.x-k8s.io/queue-name: team-a-lq
    kueue.x-k8s.io/priority-class: high-priority
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: team-a-job-high
    spec:
      restartPolicy: Never
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: gpu-workload
          image: nvidia/cuda:12.4.0-base-ubuntu22.04
          command: ["bash", "-c", "nvidia-smi && sleep 600"]
          resources:
            requests:
              nvidia.com/gpu: 4
            limits:
              nvidia.com/gpu: 4
